baseURL = "https://github.com/theninexl/bipolarArtist/"
languageCode = "es-es"
title = "Bipolar Artist"
relativeURLs = true


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true